services:
  camoufox:
    build: .
    ports:
      - "5345:5345"
    environment:
      # 设置一个你最终Gemini服务的API密钥
      - AUTH_API_KEY=sk-a5JJxmsfp6cvPKVSea5Qu5IZIg48wWSEKPMU9oIpJqI1vXkB
    volumes:
      - ./camoufox-py/config.yaml:/app/config.yaml
      - ./camoufox-py/cookies:/app/cookies
      - ./camoufox-py/logs:/app/logs
    restart: always
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true
